- name: Find latest docker compose version # noqa command-instead-of-module
  shell:
    cmd: "curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '\"tag_name\": \"\\K(.*)(?=\")'"
  register: docker_compose_latest_version
  changed_when: false

- name: Find current docker compose version
  command: "{{ docker_compose_path }} --version "
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_latest_version.stdout not in docker_compose_current_version.stdout

- name: Install docker-compose if a newer version exists
  get_url: 
    url : https://github.com/docker/compose/releases/download/{{ docker_compose_latest_version.stdout }}/docker-compose-Linux-{{ ansible_architecture }}
    dest: "{{ docker_compose_path }}"
    mode: 0755
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_latest_version.stdout not in docker_compose_current_version.stdout
